version: "3.7"
services:
  frontend:
    build: ./frontend
    image: cptfalconator/front_end:latest
    container_name: frontend
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  backend:
    build: ./backend
    image: cptfalconator/back_end:latest
    container_name: backend
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  nginx:
    build: ./nginx
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
