apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cneproject
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: cptfalconator/back_end
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: execsecrets
              key: DATABASE_URI
        - name: TEST_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: execsecrets
              key: TEST_DATABASE_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: execsecrets
              key: SECRET_KEY
