apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: cneproject
  labels: 
    app: flask
    Project: Second
spec:
  selector: 
    app: flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
