apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: cneproject
  labels:
    app: nginx
    Project: Second
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
